name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri kur
        run: |
          pip install pypdf python-docx openpyxl extract-msg pandas pyinstaller

      - name: EXE oluştur
        run: |
          pyinstaller --onefile app.py

      - name: EXE upload
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist/app.exe